import { Theme, darkTheme, lightTheme } from '@rainbow-me/rainbowkit';

export const customTheme: Theme = {
  ...lightTheme(),
  colors: {
    ...lightTheme().colors,
    accentColor: '#0ea5e9', // Sky-500
    accentColorForeground: '#ffffff',
    actionButtonBorder: '#e2e8f0',
    actionButtonBorderMobile: '#e2e8f0',
    actionButtonSecondaryBackground: '#f1f5f9',
    closeButton: '#64748b',
    closeButtonBackground: '#f1f5f9',
    connectButtonBackground: '#ffffff',
    connectButtonBackgroundError: '#fee2e2',
    connectButtonInnerBackground: '#f1f5f9',
    connectButtonText: '#1e293b',
    connectButtonTextError: '#991b1b',
    connectionIndicator: '#10b981',
    downloadBottomCardBackground: '#ffffff',
    downloadTopCardBackground: '#f8fafc',
    error: '#dc2626',
    generalBorder: '#e2e8f0',
    generalBorderDim: '#cbd5e1',
    menuItemBackground: '#f1f5f9',
    modalBackdrop: 'rgba(0, 0, 0, 0.5)',
    modalBackground: '#ffffff',
    modalBorder: '#e2e8f0',
    modalText: '#1e293b',
    modalTextDim: '#64748b',
    modalTextSecondary: '#94a3b8',
    profileAction: '#f1f5f9',
    profileActionHover: '#e2e8f0',
    profileForeground: '#ffffff',
    selectedOptionBorder: '#2563eb',
    standby: '#f59e0b',
  },
};

export const customDarkTheme: Theme = {
  ...darkTheme(),
  colors: {
    ...darkTheme().colors,
    accentColor: '#0ea5e9', // Sky-500
    accentColorForeground: '#ffffff',
    actionButtonBorder: '#334155',
    actionButtonBorderMobile: '#334155',
    actionButtonSecondaryBackground: '#1e293b',
    closeButton: '#94a3b8',
    closeButtonBackground: '#1e293b',
    connectButtonBackground: '#0f172a',
    connectButtonBackgroundError: '#7f1d1d',
    connectButtonInnerBackground: '#1e293b',
    connectButtonText: '#f1f5f9',
    connectButtonTextError: '#fecaca',
    connectionIndicator: '#10b981',
    downloadBottomCardBackground: '#0f172a',
    downloadTopCardBackground: '#1e293b',
    error: '#ef4444',
    generalBorder: '#334155',
    generalBorderDim: '#1e293b',
    menuItemBackground: '#1e293b',
    modalBackdrop: 'rgba(0, 0, 0, 0.7)',
    modalBackground: '#0f172a',
    modalBorder: '#334155',
    modalText: '#f1f5f9',
    modalTextDim: '#cbd5e1',
    modalTextSecondary: '#94a3b8',
    profileAction: '#1e293b',
    profileActionHover: '#334155',
    profileForeground: '#0f172a',
    selectedOptionBorder: '#2563eb',
    standby: '#f59e0b',
  },
};
